---
default:
  settings:
    "backupdir":
      value: "%(lgsmdir)/backups"
      desc: "Backup Directory"
    "map":
      desc: "Default map to load"
    "game_mod":
      desc: "Mod to load from gamedata/mods"
    "email":
      value: "email@example.com"
      desc: "Email address for notification"
    "emailnotification":
      value: "off"
      desc: "Email notification (on|off)"
    "engine":
      desc: "Game Engine"
    "filesdir":
      value: "%(rootdir)/serverfiles"
      desc: "Server Files Directory"
    "game":
      desc: "Name of game"
    "gamename":
      desc: "Name for subdirectory in GitHub repo"
    "ip":
      value: "0.0.0.0"
      desc: "IP Address to bind for server"
    "lgsm_version":
      value: "%(version)"
      desc: "Version of LGSM that created this config"
    "lockselfname":
      value: ".%(servicename).lock"
      desc: "LGSM Lock File"
    "logdays":
      value: "7"
      desc: "Number of days to retain logs"
    "maxplayers":
      desc: "Maximum player count"
    "port":
      desc: "Port to bind for server"
    "consolelogdir":
      value: "%(lgsmserverdir)/log/console"
      desc: "Console Log Dir"
    "consolelog":
      value: "%(consolelogdir)/%(servicename)-console.log"
      desc: "Console Log"
    "consolelogdate":
      value: "%(consolelogdir)/%(servicename)-console-`date '+%d-%m-%Y-%H-%M-%S'`.log"
      desc: "Console Log Rotation Filename"
    "scriptlogdir":
      value: "%(lgsmserverdir)/log/script"
      desc: "Script Log Dir"
    "scriptlog":
      value: "%(scriptlogdir)/%(servicename)-script.log"
      desc: "Script Log"
    "scriptlogdate":
      value: "%(scriptlogdir)/%(servicename)-script-`date '+%d-%m-%Y-%H-%M-%S'`.log"
      desc: "Script Log Rotation Filename"
    "emaillog":
      value: "%(scriptlogdir)/%(servicename)-email.log"
      desc: "Email Log"
    "servercfg_suffix":
      value: ".cfg"
      desc: "Suffix to put on the end of the server config. For file extensions, use \".ext\", setting to empty will use the bare server config name"
    "systemdir":
      value: "%(filesdir)/%(game)"
      desc: "System Directory (root of game installation)"
    "gamelogdir":
      value: "%(systemdir)/logs"
      desc: "Game log directory"
    "executabledir":
      value: "%(filesdir)"
      desc: "Executable directory"
    "executable":
      desc: "Executable to invoke to start game server"
    "servercfgdir":
      value: "%(systemdir)/cfg"
      desc: "Server config directory"
    "servercfg":
      value: "%(servicename)%(servercfg_suffix)"
      desc: "Server config file for this instance"
    "servercfgdefault":
      value: "%(servercfgdir)/lgsm-default%(servercfg_suffix)"
      desc: "Default server configuration file"
    "servercfgfullpath":
      value: "%(servercfgdir)/%(servercfg)"
      desc: "Full path to server config"
    "dependency_path":
      value: "%(filesdir)"
    "server_parms":
      desc: "Additional Server command-line arguments. Put the parameters that start with \"-\" first, then \"+\" parameters after"
  scriptactions:
    start:
      command: "command_start.sh"
      desc: "Start the server"
      aliases:
        - st
    stop:
      command: "command_stop.sh"
      desc: "Stop the server"
      aliases:
        - sp
    restart:
      command: "fn_restart"
      desc: "Restart the server"
      aliases:
        - r
    depsdetect:
      command: "command_dev_detect_deps.sh"
      desc: "Detect Dependencies"
      aliases:
        - dd
    game-dependencies:
      command: "fn_fix_game_dependencies"
      desc: "Make sure that the correct libraries for this game are installed"
      aliases:
        - gd
    update:
      command: "update_check.sh"
      desc: "Checks and applies updates from SteamCMD"
      aliases:
        - u
    update-functions:
      command: "update_functions.sh"
      desc: "Removes all functions so latest can be downloaded"
      aliases:
        - uf
    monitor:
      command: "command_monitor.sh"
      desc: "Checks that the server is running"
      aliases:
        - m
    email-test:
      command: "command_email_test.sh"
      desc: "Sends test monitor email"
      aliases:
        - et
    details:
      command: "command_details.sh"
      desc: "Displays useful infomation about the server"
      aliases:
        - d
    debug:
      command: "command_debug.sh"
      desc: "See the output of the server directly to your terminal"
    dev-debug:
      command: "command_dev_debug.sh"
      desc: "Toggle Developer Debug mode"
      aliases:
        - dev
    install:
      command: "command_install.sh"
      desc: "Install the server"
      aliases:
        - i
    auto-install:
      command: "fn_autoinstall"
      desc: "Install the server, without prompts"
      aliases:
        - ai
    backup:
      command: "command_backup.sh"
      desc: "Create archive of the server"
      aliases:
        - b
    install-mod:
      command: "install_mod.sh"
      desc: "Install mods"
      aliases:
        - im
